//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mappy.Controllers.Localization {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mappy.Controllers.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 新增标点 的本地化字符串。
        /// </summary>
        internal static string AddFlag {
            get {
                return ResourceManager.GetString("AddFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 城内以太之晶颜色 的本地化字符串。
        /// </summary>
        internal static string AethernetColor {
            get {
                return ResourceManager.GetString("AethernetColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以太之光颜色 的本地化字符串。
        /// </summary>
        internal static string AetheryteColor {
            get {
                return ResourceManager.GetString("AetheryteColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将以太之光绘制于最上层 的本地化字符串。
        /// </summary>
        internal static string AetherytesOnTop {
            get {
                return ResourceManager.GetString("AetherytesOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 团队成员 的本地化字符串。
        /// </summary>
        internal static string AllianceMembers {
            get {
                return ResourceManager.GetString("AllianceMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标悬浮时允许缩放 的本地化字符串。
        /// </summary>
        internal static string AllowZoomOnHover {
            get {
                return ResourceManager.GetString("AllowZoomOnHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总是 的本地化字符串。
        /// </summary>
        internal static string Always {
            get {
                return ResourceManager.GetString("Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总是显示工具栏 的本地化字符串。
        /// </summary>
        internal static string AlwaysShowToolbar {
            get {
                return ResourceManager.GetString("AlwaysShowToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公寓 的本地化字符串。
        /// </summary>
        internal static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前状态下无法传送 的本地化字符串。
        /// </summary>
        internal static string CannotTeleport {
            get {
                return ResourceManager.GetString("CannotTeleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图中心居中 的本地化字符串。
        /// </summary>
        internal static string CenterMap {
            get {
                return ResourceManager.GetString("CenterMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启时居中 的本地化字符串。
        /// </summary>
        internal static string CenterOnOpen {
            get {
                return ResourceManager.GetString("CenterOnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当打开地图时设置居中显示 的本地化字符串。
        /// </summary>
        internal static string CenterOnOpenHelp {
            get {
                return ResourceManager.GetString("CenterOnOpenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家居中 的本地化字符串。
        /// </summary>
        internal static string CenterOnPlayer {
            get {
                return ResourceManager.GetString("CenterOnPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 圆圈颜色 的本地化字符串。
        /// </summary>
        internal static string CircleColor {
            get {
                return ResourceManager.GetString("CircleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭地图窗口 的本地化字符串。
        /// </summary>
        internal static string CloseMapWindow {
            get {
                return ResourceManager.GetString("CloseMapWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令 的本地化字符串。
        /// </summary>
        internal static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可视范围角度 的本地化字符串。
        /// </summary>
        internal static string ConeAngle {
            get {
                return ResourceManager.GetString("ConeAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可视范围半径 的本地化字符串。
        /// </summary>
        internal static string ConeRadius {
            get {
                return ResourceManager.GetString("ConeRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定向标点 的本地化字符串。
        /// </summary>
        internal static string DirectionalMarker {
            get {
                return ResourceManager.GetString("DirectionalMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用模块 的本地化字符串。
        /// </summary>
        internal static string DisableModuleHelp {
            get {
                return ResourceManager.GetString("DisableModuleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用中 的本地化字符串。
        /// </summary>
        internal static string Disabling {
            get {
                return ResourceManager.GetString("Disabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示标点 的本地化字符串。
        /// </summary>
        internal static string DisplayedMarkers {
            get {
                return ResourceManager.GetString("DisplayedMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示职业图标 的本地化字符串。
        /// </summary>
        internal static string DisplayJobIcons {
            get {
                return ResourceManager.GetString("DisplayJobIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在地图上显示玩家的职业图标而不是选定图标 的本地化字符串。
        /// </summary>
        internal static string DisplayJobIconsHelp {
            get {
                return ResourceManager.GetString("DisplayJobIconsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示选项 的本地化字符串。
        /// </summary>
        internal static string DisplayOptions {
            get {
                return ResourceManager.GetString("DisplayOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 距离阈值 的本地化字符串。
        /// </summary>
        internal static string DistanceThreshold {
            get {
                return ResourceManager.GetString("DistanceThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预警时间 的本地化字符串。
        /// </summary>
        internal static string EarlyWarningTime {
            get {
                return ResourceManager.GetString("EarlyWarningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用集成 的本地化字符串。
        /// </summary>
        internal static string EnableIntegrations {
            get {
                return ResourceManager.GetString("EnableIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用模块 的本地化字符串。
        /// </summary>
        internal static string EnableModuleHelp {
            get {
                return ResourceManager.GetString("EnableModuleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用中 的本地化字符串。
        /// </summary>
        internal static string Enabling {
            get {
                return ResourceManager.GetString("Enabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过期颜色 的本地化字符串。
        /// </summary>
        internal static string ExpiringColor {
            get {
                return ResourceManager.GetString("ExpiringColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过期警告 的本地化字符串。
        /// </summary>
        internal static string ExpiringWarning {
            get {
                return ResourceManager.GetString("ExpiringWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半隐模式 的本地化字符串。
        /// </summary>
        internal static string FadeMode {
            get {
                return ResourceManager.GetString("FadeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半隐选项 的本地化字符串。
        /// </summary>
        internal static string FadeOptions {
            get {
                return ResourceManager.GetString("FadeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 半隐不透明度 的本地化字符串。
        /// </summary>
        internal static string FadePercent {
            get {
                return ResourceManager.GetString("FadePercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动时半隐 的本地化字符串。
        /// </summary>
        internal static string FadeWhenMoving {
            get {
                return ResourceManager.GetString("FadeWhenMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失焦时半隐 的本地化字符串。
        /// </summary>
        internal static string FadeWhenUnfocused {
            get {
                return ResourceManager.GetString("FadeWhenUnfocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临危受命 的本地化字符串。
        /// </summary>
        internal static string FATEs {
            get {
                return ResourceManager.GetString("FATEs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填充颜色 的本地化字符串。
        /// </summary>
        internal static string FillColor {
            get {
                return ResourceManager.GetString("FillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 捕鱼 的本地化字符串。
        /// </summary>
        internal static string Fishing {
            get {
                return ResourceManager.GetString("Fishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旗帜标点 的本地化字符串。
        /// </summary>
        internal static string FlagMarker {
            get {
                return ResourceManager.GetString("FlagMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接居中 的本地化字符串。
        /// </summary>
        internal static string FocusObjective {
            get {
                return ResourceManager.GetString("FocusObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当点击链接时, 居中并放大目标 的本地化字符串。
        /// </summary>
        internal static string FocusObjectiveHelp {
            get {
                return ResourceManager.GetString("FocusObjectiveHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启时跟随玩家 的本地化字符串。
        /// </summary>
        internal static string FollowOnOpen {
            get {
                return ResourceManager.GetString("FollowOnOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当打开地图时, 设置跟随玩家 的本地化字符串。
        /// </summary>
        internal static string FollowOnOpenHelp {
            get {
                return ResourceManager.GetString("FollowOnOpenHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟随玩家 的本地化字符串。
        /// </summary>
        internal static string FollowPlayer {
            get {
                return ResourceManager.GetString("FollowPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏功能集成 的本地化字符串。
        /// </summary>
        internal static string GameIntegrations {
            get {
                return ResourceManager.GetString("GameIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集区域 的本地化字符串。
        /// </summary>
        internal static string GatheringArea {
            get {
                return ResourceManager.GetString("GatheringArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集点 的本地化字符串。
        /// </summary>
        internal static string GatheringPoints {
            get {
                return ResourceManager.GetString("GatheringPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一般 的本地化字符串。
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金币 的本地化字符串。
        /// </summary>
        internal static string gil {
            get {
                return ResourceManager.GetString("gil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 居中地图于指定的 XY 坐标上 的本地化字符串。
        /// </summary>
        internal static string GoToCommandHelp {
            get {
                return ResourceManager.GetString("GoToCommandHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收获 的本地化字符串。
        /// </summary>
        internal static string Harvesting {
            get {
                return ResourceManager.GetString("Harvesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示该帮助信息 的本地化字符串。
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏已接取的任务 的本地化字符串。
        /// </summary>
        internal static string HideAcceptedQuests {
            get {
                return ResourceManager.GetString("HideAcceptedQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏边框并锁定窗口 的本地化字符串。
        /// </summary>
        internal static string HideAndLock {
            get {
                return ResourceManager.GetString("HideAndLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过图时隐藏 的本地化字符串。
        /// </summary>
        internal static string HideBetweenAreas {
            get {
                return ResourceManager.GetString("HideBetweenAreas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 战斗时隐藏 的本地化字符串。
        /// </summary>
        internal static string HideInCombat {
            get {
                return ResourceManager.GetString("HideInCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 副本内隐藏 的本地化字符串。
        /// </summary>
        internal static string HideInDuties {
            get {
                return ResourceManager.GetString("HideInDuties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏理符任务 的本地化字符串。
        /// </summary>
        internal static string HideLeveQuests {
            get {
                return ResourceManager.GetString("HideLeveQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏未接取的任务 的本地化字符串。
        /// </summary>
        internal static string HideUnacceptedQuests {
            get {
                return ResourceManager.GetString("HideUnacceptedQuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏边框 的本地化字符串。
        /// </summary>
        internal static string HideWindowFrame {
            get {
                return ResourceManager.GetString("HideWindowFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏游戏原生界面 的本地化字符串。
        /// </summary>
        internal static string HideWithGameGui {
            get {
                return ResourceManager.GetString("HideWithGameGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 敌对目标 的本地化字符串。
        /// </summary>
        internal static string Hostiles {
            get {
                return ResourceManager.GetString("Hostiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房屋 的本地化字符串。
        /// </summary>
        internal static string HousingMarkers {
            get {
                return ResourceManager.GetString("HousingMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标设置 的本地化字符串。
        /// </summary>
        internal static string IconConfig {
            get {
                return ResourceManager.GetString("IconConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此处用于禁用 Mappy 已显示过的任何图标, 未显示过的图标无法禁用 的本地化字符串。
        /// </summary>
        internal static string IconDisableInfo {
            get {
                return ResourceManager.GetString("IconDisableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还未显示过任何图标, 请打开地图以获取图标数据 的本地化字符串。
        /// </summary>
        internal static string IconDisableNoIcons {
            get {
                return ResourceManager.GetString("IconDisableNoIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放 的本地化字符串。
        /// </summary>
        internal static string IconScale {
            get {
                return ResourceManager.GetString("IconScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标选择 的本地化字符串。
        /// </summary>
        internal static string IconSelection {
            get {
                return ResourceManager.GetString("IconSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略 Esc 键 的本地化字符串。
        /// </summary>
        internal static string IgnoreEscapeKey {
            get {
                return ResourceManager.GetString("IgnoreEscapeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁止 Esc 键关闭地图窗口 的本地化字符串。
        /// </summary>
        internal static string IgnoreEscapeKeyHelp {
            get {
                return ResourceManager.GetString("IgnoreEscapeKeyHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略任务日志设置 的本地化字符串。
        /// </summary>
        internal static string IgnoreJournalSetting {
            get {
                return ResourceManager.GetString("IgnoreJournalSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启后, 即使你在任务日志中设置隐藏了某个任务, 地图仍然会显示全部的任务图标 的本地化字符串。
        /// </summary>
        internal static string IgnoreJournalSettingHelp {
            get {
                return ResourceManager.GetString("IgnoreJournalSettingHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 活跃任务颜色 的本地化字符串。
        /// </summary>
        internal static string InProgressColor {
            get {
                return ResourceManager.GetString("InProgressColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 副本区链接颜色 的本地化字符串。
        /// </summary>
        internal static string InstanceLinkColor {
            get {
                return ResourceManager.GetString("InstanceLinkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以插件功能替代所有一般的游戏原生地图功能 的本地化字符串。
        /// </summary>
        internal static string IntegrationsDescription {
            get {
                return ResourceManager.GetString("IntegrationsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无人岛 的本地化字符串。
        /// </summary>
        internal static string IslandSanctuary {
            get {
                return ResourceManager.GetString("IslandSanctuary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保持开启 的本地化字符串。
        /// </summary>
        internal static string KeepOpen {
            get {
                return ResourceManager.GetString("KeepOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 层级 的本地化字符串。
        /// </summary>
        internal static string Layer {
            get {
                return ResourceManager.GetString("Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制标点绘制的优先级, 较高的值会被优先绘制 的本地化字符串。
        /// </summary>
        internal static string LayerHelp {
            get {
                return ResourceManager.GetString("LayerHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 理符任务颜色 的本地化字符串。
        /// </summary>
        internal static string LeveQuestColor {
            get {
                return ResourceManager.GetString("LeveQuestColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 锁定窗口位置 的本地化字符串。
        /// </summary>
        internal static string LockWindow {
            get {
                return ResourceManager.GetString("LockWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录 的本地化字符串。
        /// </summary>
        internal static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图 的本地化字符串。
        /// </summary>
        internal static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图层级 的本地化字符串。
        /// </summary>
        internal static string MapLayers {
            get {
                return ResourceManager.GetString("MapLayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图链接颜色 的本地化字符串。
        /// </summary>
        internal static string MapLinkColor {
            get {
                return ResourceManager.GetString("MapLinkColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图标点 的本地化字符串。
        /// </summary>
        internal static string MapMarkers {
            get {
                return ResourceManager.GetString("MapMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采掘 的本地化字符串。
        /// </summary>
        internal static string Mining {
            get {
                return ResourceManager.GetString("Mining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他标点 的本地化字符串。
        /// </summary>
        internal static string MiscMarkers {
            get {
                return ResourceManager.GetString("MiscMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块颜色设置 的本地化字符串。
        /// </summary>
        internal static string ModuleColors {
            get {
                return ResourceManager.GetString("ModuleColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块设置 的本地化字符串。
        /// </summary>
        internal static string ModuleConfig {
            get {
                return ResourceManager.GetString("ModuleConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块选项 的本地化字符串。
        /// </summary>
        internal static string ModuleOptions {
            get {
                return ResourceManager.GetString("ModuleOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块 的本地化字符串。
        /// </summary>
        internal static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动标点至此处 的本地化字符串。
        /// </summary>
        internal static string MoveFlag {
            get {
                return ResourceManager.GetString("MoveFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从不 的本地化字符串。
        /// </summary>
        internal static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前地图无绘制层级 的本地化字符串。
        /// </summary>
        internal static string NoLayersInfo {
            get {
                return ResourceManager.GetString("NoLayersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启设置界面 的本地化字符串。
        /// </summary>
        internal static string OpenConfigWindow {
            get {
                return ResourceManager.GetString("OpenConfigWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启 IPC Demo 的本地化字符串。
        /// </summary>
        internal static string OpenIPCDemo {
            get {
                return ResourceManager.GetString("OpenIPCDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开地图窗口 的本地化字符串。
        /// </summary>
        internal static string OpenMapWindow {
            get {
                return ResourceManager.GetString("OpenMapWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮廓颜色 的本地化字符串。
        /// </summary>
        internal static string OutlineColor {
            get {
                return ResourceManager.GetString("OutlineColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轮廓粗细 的本地化字符串。
        /// </summary>
        internal static string OutlineThickness {
            get {
                return ResourceManager.GetString("OutlineThickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小队成员 的本地化字符串。
        /// </summary>
        internal static string PartyMembers {
            get {
                return ResourceManager.GetString("PartyMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宠物 的本地化字符串。
        /// </summary>
        internal static string Pets {
            get {
                return ResourceManager.GetString("Pets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家 的本地化字符串。
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 号 的本地化字符串。
        /// </summary>
        internal static string Plot {
            get {
                return ResourceManager.GetString("Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插件联动 的本地化字符串。
        /// </summary>
        internal static string PluginIntegrations {
            get {
                return ResourceManager.GetString("PluginIntegrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度 的本地化字符串。
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mappy 在 PVP 区域内不可用 的本地化字符串。
        /// </summary>
        internal static string PvPError {
            get {
                return ResourceManager.GetString("PvPError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 碎石 的本地化字符串。
        /// </summary>
        internal static string Quarrying {
            get {
                return ResourceManager.GetString("Quarrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 任务 的本地化字符串。
        /// </summary>
        internal static string QuestMarkers {
            get {
                return ResourceManager.GetString("QuestMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除命令标点 的本地化字符串。
        /// </summary>
        internal static string RemoveCommandMarker {
            get {
                return ResourceManager.GetString("RemoveCommandMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除标点 的本地化字符串。
        /// </summary>
        internal static string RemoveFlag {
            get {
                return ResourceManager.GetString("RemoveFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除标记区域 的本地化字符串。
        /// </summary>
        internal static string RemoveGatheringArea {
            get {
                return ResourceManager.GetString("RemoveGatheringArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移除任务标点 的本地化字符串。
        /// </summary>
        internal static string RemoveQuestMarker {
            get {
                return ResourceManager.GetString("RemoveQuestMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 忽略地图缩放 的本地化字符串。
        /// </summary>
        internal static string ScaleCone {
            get {
                return ResourceManager.GetString("ScaleCone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启后, 地图缩放将不会影响可视范围的显示大小 的本地化字符串。
        /// </summary>
        internal static string ScaleConeHelp {
            get {
                return ResourceManager.GetString("ScaleConeHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据地区搜索 的本地化字符串。
        /// </summary>
        internal static string SearchByRegion {
            get {
                return ResourceManager.GetString("SearchByRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在地图中搜索 的本地化字符串。
        /// </summary>
        internal static string SearchForMap {
            get {
                return ResourceManager.GetString("SearchForMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索... 的本地化字符串。
        /// </summary>
        internal static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示边框并解除锁定 的本地化字符串。
        /// </summary>
        internal static string ShowAndUnlock {
            get {
                return ResourceManager.GetString("ShowAndUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示可视范围 的本地化字符串。
        /// </summary>
        internal static string ShowCone {
            get {
                return ResourceManager.GetString("ShowCone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示房屋编号 的本地化字符串。
        /// </summary>
        internal static string ShowHousingNumber {
            get {
                return ResourceManager.GetString("ShowHousingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示图标 的本地化字符串。
        /// </summary>
        internal static string ShowIcon {
            get {
                return ResourceManager.GetString("ShowIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示地图名称 的本地化字符串。
        /// </summary>
        internal static string ShowMapName {
            get {
                return ResourceManager.GetString("ShowMapName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示附加提示信息 的本地化字符串。
        /// </summary>
        internal static string ShowMiscTooltips {
            get {
                return ResourceManager.GetString("ShowMiscTooltips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为类似&quot;修理&quot;, &quot;交易&quot;等的图标显示附加提示信息 的本地化字符串。
        /// </summary>
        internal static string ShowMiscTooltipsHelp {
            get {
                return ResourceManager.GetString("ShowMiscTooltipsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示圆圈 的本地化字符串。
        /// </summary>
        internal static string ShowRing {
            get {
                return ResourceManager.GetString("ShowRing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示传送费 的本地化字符串。
        /// </summary>
        internal static string ShowTeleportCosts {
            get {
                return ResourceManager.GetString("ShowTeleportCosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标悬浮时显示工具栏 的本地化字符串。
        /// </summary>
        internal static string ShowToolbarOnHover {
            get {
                return ResourceManager.GetString("ShowToolbarOnHover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示提示信息 的本地化字符串。
        /// </summary>
        internal static string ShowTooltip {
            get {
                return ResourceManager.GetString("ShowTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准标记颜色 的本地化字符串。
        /// </summary>
        internal static string StandardColor {
            get {
                return ResourceManager.GetString("StandardColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送 的本地化字符串。
        /// </summary>
        internal static string Teleport {
            get {
                return ResourceManager.GetString("Teleport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送费用 的本地化字符串。
        /// </summary>
        internal static string TeleportCost {
            get {
                return ResourceManager.GetString("TeleportCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要使用传送功能, 必须安装并启用 Teleporter 插件 的本地化字符串。
        /// </summary>
        internal static string TeleporterMissingError {
            get {
                return ResourceManager.GetString("TeleporterMissingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传送至 {0} 的本地化字符串。
        /// </summary>
        internal static string TeleportingToLocation {
            get {
                return ResourceManager.GetString("TeleportingToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未找到传送 IPC 的本地化字符串。
        /// </summary>
        internal static string TeleportIPCNotFound {
            get {
                return ResourceManager.GetString("TeleportIPCNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 临时标点 的本地化字符串。
        /// </summary>
        internal static string TemporaryMarkers {
            get {
                return ResourceManager.GetString("TemporaryMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剩余时间 的本地化字符串。
        /// </summary>
        internal static string TimeRemaining {
            get {
                return ResourceManager.GetString("TimeRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换地图窗口开启状态 的本地化字符串。
        /// </summary>
        internal static string ToggleMapWindow {
            get {
                return ResourceManager.GetString("ToggleMapWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换模块开启状态 的本地化字符串。
        /// </summary>
        internal static string ToggleModuleHelp {
            get {
                return ResourceManager.GetString("ToggleModuleHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具栏选项 的本地化字符串。
        /// </summary>
        internal static string ToolbarOptions {
            get {
                return ResourceManager.GetString("ToolbarOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示信息颜色 的本地化字符串。
        /// </summary>
        internal static string TooltipColor {
            get {
                return ResourceManager.GetString("TooltipColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示信息设置 的本地化字符串。
        /// </summary>
        internal static string TooltipConfig {
            get {
                return ResourceManager.GetString("TooltipConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 埋藏的宝藏 的本地化字符串。
        /// </summary>
        internal static string TreasureMarkers {
            get {
                return ResourceManager.GetString("TreasureMarkers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未接取任务的颜色 的本地化字符串。
        /// </summary>
        internal static string UnacceptedQuestColor {
            get {
                return ResourceManager.GetString("UnacceptedQuestColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用命令后展开窗口 的本地化字符串。
        /// </summary>
        internal static string UnCollapseWindow {
            get {
                return ResourceManager.GetString("UnCollapseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用区域搜索 的本地化字符串。
        /// </summary>
        internal static string UseRegionSearch {
            get {
                return ResourceManager.GetString("UseRegionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找地图时使用替代的搜索 UI 的本地化字符串。
        /// </summary>
        internal static string UseRegionSearchHelp {
            get {
                return ResourceManager.GetString("UseRegionSearchHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 场景标记 的本地化字符串。
        /// </summary>
        internal static string Waymarks {
            get {
                return ResourceManager.GetString("Waymarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 聚焦时 的本地化字符串。
        /// </summary>
        internal static string WhenFocused {
            get {
                return ResourceManager.GetString("WhenFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动时 的本地化字符串。
        /// </summary>
        internal static string WhenMoving {
            get {
                return ResourceManager.GetString("WhenMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失焦时 的本地化字符串。
        /// </summary>
        internal static string WhenUnFocused {
            get {
                return ResourceManager.GetString("WhenUnFocused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地图窗口选项 的本地化字符串。
        /// </summary>
        internal static string WindowOptions {
            get {
                return ResourceManager.GetString("WindowOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口位置 的本地化字符串。
        /// </summary>
        internal static string WindowPosition {
            get {
                return ResourceManager.GetString("WindowPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口大小 的本地化字符串。
        /// </summary>
        internal static string WindowSize {
            get {
                return ResourceManager.GetString("WindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放标点 的本地化字符串。
        /// </summary>
        internal static string ZoomOnFlag {
            get {
                return ResourceManager.GetString("ZoomOnFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当点击地图链接时, 缩放至标点 的本地化字符串。
        /// </summary>
        internal static string ZoomOnFlagHelp {
            get {
                return ResourceManager.GetString("ZoomOnFlagHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放选项 的本地化字符串。
        /// </summary>
        internal static string ZoomOptions {
            get {
                return ResourceManager.GetString("ZoomOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放速度 的本地化字符串。
        /// </summary>
        internal static string ZoomSpeed {
            get {
                return ResourceManager.GetString("ZoomSpeed", resourceCulture);
            }
        }
    }
}
